// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbbRS2GifiBkOFaPrJX-11ePTWrqPFMg4',
    appId: '1:1005167792462:web:1ef6b280c9d336a946ce1f',
    messagingSenderId: '1005167792462',
    projectId: 'ai-food-calorie-a0085',
    authDomain: 'ai-food-calorie-a0085.firebaseapp.com',
    storageBucket: 'ai-food-calorie-a0085.firebasestorage.app',
    measurementId: 'G-W8KJPGGH5B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCiji0ldLjrFcM_ollGbifSTCferZMnufE',
    appId: '1:1005167792462:android:24ba9fad2fdea37c46ce1f',
    messagingSenderId: '1005167792462',
    projectId: 'ai-food-calorie-a0085',
    storageBucket: 'ai-food-calorie-a0085.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA541CSSH01_cK2sVzsWSheZJuXoCYxm1k',
    appId: '1:1005167792462:ios:7810a82700e7609a46ce1f',
    messagingSenderId: '1005167792462',
    projectId: 'ai-food-calorie-a0085',
    storageBucket: 'ai-food-calorie-a0085.firebasestorage.app',
    iosBundleId: 'com.example.aiFoodCalorie',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA541CSSH01_cK2sVzsWSheZJuXoCYxm1k',
    appId: '1:1005167792462:ios:7810a82700e7609a46ce1f',
    messagingSenderId: '1005167792462',
    projectId: 'ai-food-calorie-a0085',
    storageBucket: 'ai-food-calorie-a0085.firebasestorage.app',
    iosBundleId: 'com.example.aiFoodCalorie',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBbbRS2GifiBkOFaPrJX-11ePTWrqPFMg4',
    appId: '1:1005167792462:web:7d75ea7bc753f35346ce1f',
    messagingSenderId: '1005167792462',
    projectId: 'ai-food-calorie-a0085',
    authDomain: 'ai-food-calorie-a0085.firebaseapp.com',
    storageBucket: 'ai-food-calorie-a0085.firebasestorage.app',
    measurementId: 'G-GHDHG2JZZH',
  );
}
